services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    volumes:
      - ./keycloak:/opt/keycloak/data
    healthcheck:
      # https://gist.github.com/sarath-soman/5d9aec06953bbd0990c648605d4dba07?permalink_comment_id=5120472#gistcomment-5120472
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: nginx
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      oauth2-proxy:
        condition: service_healthy

  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
  
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    container_name: oauth2-proxy
    command:
      - --http-address=0.0.0.0:4180
      - --upstream=http://httpbin:80
      - --scope=openid email profile
      # Error creating session during OAuth2 callback: audience from claim aud with value [account] does not match with any of allowed audiences map[myapp:{}]
      - --oidc-audience-claim=azp
      - --provider=keycloak-oidc
      - --client-id=myapp
      - --redirect-url=http://localhost:4180/oauth2/callback
      - --oidc-issuer-url=http://keycloak:8080/realms/myrealm
      - --email-domain=*
      - --code-challenge-method=S256

      # https://github.com/oauth2-proxy/oauth2-proxy/issues/1712#issuecomment-1173659513
      - --insecure-oidc-allow-unverified-email=true
    ports:
      - "4180:4180"
      - "443:443"
    environment:
      # productionで使用するときはシークレットを環境変数として設定する
      OAUTH2_PROXY_CLIENT_SECRET: "xS4lByozdi2cFKJXGVlXKvToHbcyKapY"
      OAUTH2_PROXY_COOKIE_SECRET: "wMnBzwOOLmEJjTm59oV2dtIrsIdaYOwzMVeYVzkABsk"

    # Keycloakが先に起動していないとエラーが発生するためdepends_onを設定
    depends_on:
      keycloak:
        condition: service_healthy
    
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider localhost:4180/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  