services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    volumes:
      - ./keycloak:/opt/keycloak/data