---
services:
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    environment:
      # AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      # AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      # AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      X_AUTHELIA_CONFIG_FILTERS: 'template'
    volumes:
      - '${PWD}/authelia/config:/config'
      - '${PWD}/authelia/secrets:/secrets'
      - '${PWD}/authelia/keys:/keys'
    ports:
      - '9091:9091'
