[env]
# golang API + Keycloak
KC_REALM = "myrealm"
KC_CLIENT_ID = "myapp"
KC_CLIENT_SECRET = "6ejgXdjwYOs3WKsaoiGO21OfalJgzrPs"
KC_ISSUER_URL = "http://localhost:8080/realms/myrealm"
BASE_URL = "http://localhost:8081"
REDIRECT_URL="http://localhost:8081/callback"

# Keycloak が ID トークンを JWE にするための公開鍵
TF_VAR_jwks_url="http://host.docker.internal:8081/jwks"

# Next.js Better Auth + Keycloak
BETTER_AUTH_SECRET="oOtSMPRcng9ePWRUSR7WZ0Aaufk4MGleIqfI18ZYxsc="
BETTER_AUTH_URL="http://localhost:3000"
KEYCLOAK_CLIENT_ID="better-auth-client"
KEYCLOAK_CLIENT_SECRET="ZgbF4A06i4CsUM1W5jdkfHusCuokZ0vW"
KEYCLOAK_ISSUER="http://localhost:8080/realms/myrealm"

[tools]
node = "24.14.1"
pnpm = "10.33.0"
terraform = "1.14.3"
