[project]
name = "pydantic-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings>=2.6.1",
    "pydantic>=2.9.2",
]

[dependency-groups]
lint = [
    "ruff>=0.7.4",
]
dev = [
    "ruff>=0.7.4",
]
