FROM golang:1.24.6-alpine3.22 AS build

WORKDIR /go/src/app
COPY src/ .

RUN go mod download

RUN CGO_ENABLED=0 go build -o /go/bin/app

FROM gcr.io/distroless/static-debian12

COPY --from=build /go/bin/app /
CMD ["/app"]