FROM golang:1.24.6-alpine3.22 AS build

WORKDIR /go/src/app
COPY src/ .

RUN go mod download

RUN CGO_ENABLED=0 go build -o bootstrap .

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=build /go/src/app/bootstrap ${LAMBDA_TASK_ROOT}
CMD ["bootstrap"]