CREATE TABLE "casbin_rule" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "casbin_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ptype" varchar(255),
	"v0" varchar(255),
	"v1" varchar(255),
	"v2" varchar(255),
	"v3" varchar(255),
	"v4" varchar(255),
	"v5" varchar(255)
);
--> statement-breakpoint
INSERT INTO "casbin_rule" ("ptype", "v0", "v1", "v2") VALUES
	('p', 'member', 'create', 'allow'),
	('p', 'manager', 'create', 'allow'),
	('p', 'admin', 'create', 'allow'),
	('p', 'member', 'view', 'allow'),
	('p', 'manager', 'view', 'allow'),
	('p', 'admin', 'view', 'allow'),
	('p', 'member', 'viewReceipt', 'allow'),
	('p', 'manager', 'viewReceipt', 'allow'),
	('p', 'admin', 'viewReceipt', 'allow'),
	('p', 'member', 'edit', 'allow'),
	('p', 'manager', 'edit', 'allow'),
	('p', 'admin', 'edit', 'allow'),
	('p', 'member', 'submit', 'allow'),
	('p', 'manager', 'submit', 'allow'),
	('p', 'admin', 'submit', 'allow'),
	('p', 'member', 'withdraw', 'allow'),
	('p', 'manager', 'withdraw', 'allow'),
	('p', 'admin', 'withdraw', 'allow'),
	('p', 'member', 'delete', 'allow'),
	('p', 'manager', 'delete', 'allow'),
	('p', 'admin', 'delete', 'allow'),
	('p', 'manager', 'approve', 'allow'),
	('p', 'admin', 'approve', 'allow'),
	('p', 'manager', 'reject', 'allow'),
	('p', 'admin', 'reject', 'allow'),
	('p', 'admin', 'invalidate', 'allow'),
	('p', 'admin', 'settle', 'allow');
