apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.1.1/manifests/install.yaml
- ./namespace.yaml

patchesStrategicMerge:
- ./argocd-notifications-secret.yaml
- ./argocd-notifications-cm.yaml