---
- hosts: localhost
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: aws_ssm
    ansible_aws_ssm_instance_id: i-0a12687643b2bf362
    ansible_aws_ssm_bucket_name: ansible-bucket-fkejsj
  tasks:
    - name: Install a Nginx Package
      ansible.builtin.apt:
        name: nginx
        state: present