apiVersion: v1
kind: ConfigMap
metadata:
  name: semver-compare-hyphen-ranges
data:
  # バージョン範囲のテスト（カンマ区切り）
  test01_condition: '{{`{{ semverCompare ">=1.2.0, <1.3.0" "1.2.3" }}`}}'
  test01_result: {{ semverCompare ">=1.2.0, <1.3.0" "1.2.3" }}
  
  test02_condition: '{{`{{ semverCompare ">=1.2.0, <1.3.0" "1.3.0" }}`}}'
  test02_result: {{ semverCompare ">=1.2.0, <1.3.0" "1.3.0" }}
  
  # ハイフン範囲のテスト
  # 1.2 - 1.4.5 は >= 1.2 <= 1.4.5 と同等
  test03_condition: '{{`{{ semverCompare "1.2 - 1.4.5" "1.3.0" }}`}}'
  test03_result: {{ semverCompare "1.2 - 1.4.5" "1.3.0" }}
  
  test04_condition: '{{`{{ semverCompare "1.2 - 1.4.5" "1.2.0" }}`}}'
  test04_result: {{ semverCompare "1.2 - 1.4.5" "1.2.0" }}
  
  test05_condition: '{{`{{ semverCompare "1.2 - 1.4.5" "1.4.5" }}`}}'
  test05_result: {{ semverCompare "1.2 - 1.4.5" "1.4.5" }}
  
  test06_condition: '{{`{{ semverCompare "1.2 - 1.4.5" "1.5.0" }}`}}'
  test06_result: {{ semverCompare "1.2 - 1.4.5" "1.5.0" }}
  
  test07_condition: '{{`{{ semverCompare "1.2 - 1.4.5" "1.1.9" }}`}}'
  test07_result: {{ semverCompare "1.2 - 1.4.5" "1.1.9" }}
  
  # 2.3.4 - 4.5 は >= 2.3.4 <= 4.5 と同等
  test08_condition: '{{`{{ semverCompare "2.3.4 - 4.5" "3.0.0" }}`}}'
  test08_result: {{ semverCompare "2.3.4 - 4.5" "3.0.0" }}
  
  test09_condition: '{{`{{ semverCompare "2.3.4 - 4.5" "2.3.4" }}`}}'
  test09_result: {{ semverCompare "2.3.4 - 4.5" "2.3.4" }}
  
  test10_condition: '{{`{{ semverCompare "2.3.4 - 4.5" "4.5.0" }}`}}'
  test10_result: {{ semverCompare "2.3.4 - 4.5" "4.5.0" }}
  
  test11_condition: '{{`{{ semverCompare "2.3.4 - 4.5" "4.6.0" }}`}}'
  test11_result: {{ semverCompare "2.3.4 - 4.5" "4.6.0" }}
  
  test12_condition: '{{`{{ semverCompare "2.3.4 - 4.5" "2.3.3" }}`}}'
  test12_result: {{ semverCompare "2.3.4 - 4.5" "2.3.3" }}
  
  # ハイフン範囲とプレリリースの組み合わせ
  test13_condition: '{{`{{ semverCompare "1.2.0 - 1.4.0" "1.3.0-beta" }}`}}'
  test13_result: {{ semverCompare "1.2.0 - 1.4.0" "1.3.0-beta" }}
  
  test14_condition: '{{`{{ semverCompare "1.2.0-0 - 1.4.0" "1.3.0-beta" }}`}}'
  test14_result: {{ semverCompare "1.2.0-0 - 1.4.0" "1.3.0-beta" }}

  test15_condition: '{{`{{ semverCompare "1.2.0-0 - 1.4.0-0" "1.3.0-beta" }}`}}'
  test15_result: {{ semverCompare "1.2.0-0 - 1.4.0-0" "1.3.0-beta" }}