apiVersion: v1
kind: ConfigMap
metadata:
  name: semver-compare-caret
data:
  # ^1.2.3 は >= 1.2.3, < 2.0.0 と同等（メジャーバージョン1の範囲内）
  test01_condition: '{{`{{ semverCompare "^1.2.3" "1.2.3" }}`}}'
  test01_result: {{ semverCompare "^1.2.3" "1.2.3" }}
  
  test02_condition: '{{`{{ semverCompare "^1.2.3" "1.9.9" }}`}}'
  test02_result: {{ semverCompare "^1.2.3" "1.9.9" }}
  
  test03_condition: '{{`{{ semverCompare "^1.2.3" "2.0.0" }}`}}'
  test03_result: {{ semverCompare "^1.2.3" "2.0.0" }}
  
  # ^0.2.3 は >=0.2.3, <0.3.0 と同等（マイナーバージョン0.2の範囲内）
  test04_condition: '{{`{{ semverCompare "^0.2.3" "0.2.3" }}`}}'
  test04_result: {{ semverCompare "^0.2.3" "0.2.3" }}
  
  test05_condition: '{{`{{ semverCompare "^0.2.3" "0.2.9" }}`}}'
  test05_result: {{ semverCompare "^0.2.3" "0.2.9" }}
  
  test06_condition: '{{`{{ semverCompare "^0.2.3" "0.3.0" }}`}}'
  test06_result: {{ semverCompare "^0.2.3" "0.3.0" }}
  
  # ^0.0.3 は >=0.0.3, <0.0.4 と同等（パッチバージョン0.0.3のみ）
  test07_condition: '{{`{{ semverCompare "^0.0.3" "0.0.3" }}`}}'
  test07_result: {{ semverCompare "^0.0.3" "0.0.3" }}
  
  test08_condition: '{{`{{ semverCompare "^0.0.3" "0.0.4" }}`}}'
  test08_result: {{ semverCompare "^0.0.3" "0.0.4" }}
  
  # ワイルドカードとの組み合わせ
  test09_condition: '{{`{{ semverCompare "^1.2.x" "1.5.0" }}`}}'
  test09_result: {{ semverCompare "^1.2.x" "1.5.0" }}
  
  test10_condition: '{{`{{ semverCompare "^2.x" "2.9.9" }}`}}'
  test10_result: {{ semverCompare "^2.x" "2.9.9" }}
  
  test11_condition: '{{`{{ semverCompare "^2.x" "3.0.0" }}`}}'
  test11_result: {{ semverCompare "^2.x" "3.0.0" }}
  
  # 他のパターン
  test12_condition: '{{`{{ semverCompare "^0.2" "0.2.5" }}`}}'
  test12_result: {{ semverCompare "^0.2" "0.2.5" }}
  
  test13_condition: '{{`{{ semverCompare "^0" "0.9.9" }}`}}'
  test13_result: {{ semverCompare "^0" "0.9.9" }}
  
  test14_condition: '{{`{{ semverCompare "^0" "1.0.0" }}`}}'
  test14_result: {{ semverCompare "^0" "1.0.0" }}
  
  # プレリリースバージョンとの組み合わせ
  test15_condition: '{{`{{ semverCompare "^1.2.0" "1.3.0-beta" }}`}}'
  test15_result: {{ semverCompare "^1.2.0" "1.3.0-beta" }}
  
  test16_condition: '{{`{{ semverCompare "^1.2.0-0" "1.3.0-beta" }}`}}'
  test16_result: {{ semverCompare "^1.2.0-0" "1.3.0-beta" }}
  
  test17_condition: '{{`{{ semverCompare "^0.2.0-0" "0.2.3-beta" }}`}}'
  test17_result: {{ semverCompare "^0.2.0-0" "0.2.3-beta" }}
  
  test18_condition: '{{`{{ semverCompare "^0.2.0-0" "0.3.0-alpha" }}`}}'
  test18_result: {{ semverCompare "^0.2.0-0" "0.3.0-alpha" }}
