apiVersion: v1
kind: ConfigMap
metadata:
  name: semver-compare-tilde
data:
  # ~1.2.3 は >= 1.2.3, < 1.3.0 と同等
  test01_condition: '{{`{{ semverCompare "~1.2.3" "1.2.3" }}`}}'
  test01_result: {{ semverCompare "~1.2.3" "1.2.3" }}
  
  test02_condition: '{{`{{ semverCompare "~1.2.3" "1.2.9" }}`}}'
  test02_result: {{ semverCompare "~1.2.3" "1.2.9" }}
  
  test03_condition: '{{`{{ semverCompare "~1.2.3" "1.3.0" }}`}}'
  test03_result: {{ semverCompare "~1.2.3" "1.3.0" }}
  
  # ~1 は >= 1, < 2 と同等
  test04_condition: '{{`{{ semverCompare "~1" "1.0.0" }}`}}'
  test04_result: {{ semverCompare "~1" "1.0.0" }}
  
  test05_condition: '{{`{{ semverCompare "~1" "1.9.9" }}`}}'
  test05_result: {{ semverCompare "~1" "1.9.9" }}
  
  test06_condition: '{{`{{ semverCompare "~1" "2.0.0" }}`}}'
  test06_result: {{ semverCompare "~1" "2.0.0" }}
  
  # ~2.3 は >= 2.3, < 2.4 と同等
  test07_condition: '{{`{{ semverCompare "~2.3" "2.3.0" }}`}}'
  test07_result: {{ semverCompare "~2.3" "2.3.0" }}
  
  test08_condition: '{{`{{ semverCompare "~2.3" "2.3.9" }}`}}'
  test08_result: {{ semverCompare "~2.3" "2.3.9" }}
  
  test09_condition: '{{`{{ semverCompare "~2.3" "2.4.0" }}`}}'
  test09_result: {{ semverCompare "~2.3" "2.4.0" }}
  
  # ~1.2.x は >= 1.2.0, < 1.3.0 と同等
  test10_condition: '{{`{{ semverCompare "~1.2.x" "1.2.7" }}`}}'
  test10_result: {{ semverCompare "~1.2.x" "1.2.7" }}
  
  test11_condition: '{{`{{ semverCompare "~1.2.x" "1.3.0" }}`}}'
  test11_result: {{ semverCompare "~1.2.x" "1.3.0" }}
  
  # ~1.x は >= 1, < 2 と同等
  test12_condition: '{{`{{ semverCompare "~1.x" "1.9.9" }}`}}'
  test12_result: {{ semverCompare "~1.x" "1.9.9" }}
  
  test13_condition: '{{`{{ semverCompare "~1.x" "2.0.0" }}`}}'
  test13_result: {{ semverCompare "~1.x" "2.0.0" }}

  # プレリリースバージョンとの組み合わせ
  test14_condition: '{{`{{ semverCompare "~1.2.0" "1.2.0-beta" }}`}}'
  test14_result: {{ semverCompare "~1.2.0" "1.2.0-beta" }}
  
  test15_condition: '{{`{{ semverCompare "~1.2.0-0" "1.2.0-beta" }}`}}'
  test15_result: {{ semverCompare "~1.2.0-0" "1.2.0-beta" }}
  
  test16_condition: '{{`{{ semverCompare "~1.2.0-0" "1.2.5-alpha" }}`}}'
  test16_result: {{ semverCompare "~1.2.0-0" "1.2.5-alpha" }}
  
  test17_condition: '{{`{{ semverCompare "~1.2.0-0" "1.3.0-alpha" }}`}}'
  test17_result: {{ semverCompare "~1.2.0-0" "1.3.0-alpha" }}