name: Deploy ECR from GitHub Action

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE_ECR }}
          aws-region: ap-northeast-1
          role-session-name: github-actions-session

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: lambda-container-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd github-actions-ecr-lambda-container-deploy
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG